# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# encoding of filenames
encoding: utf-8

# Permalinks
permalink: pretty

# If not set custom url: if user pages, then use "/"; if project page, use "/project-name" (without trailing slash).
baseurl: /
url: http://blog.fxhu.tk
paginate: 5

# Site info
title: '顽石@灵河'
tagline: '食色，性也！'
description: '蓬莱、方丈、瀛洲'



# About/contact
author:
  name: '顽石'
  email: 'youwu@inventati.org'

# Custom vars
version: '壹零壹'
