# https://help.github.com/articles/configuring-jekyll/

encoding: utf-8

url: http://blog.fxhu.tk
baseurl: ''

permalink: pretty

paginate: 5

title: '灵河顽石'
tagline: '食色，性也'
description: '蓬莱、方丈、瀛洲 <a href="mailto:{{ site.author.email }}"><br>（@信）</a>'

author:
  name: '灵河顽石'
  email: youwu@inventati.org

# Custom vars
version: '壹零壹'
